po-map appa_en.po appa_zh.po zh.po
po-map appb_en.po appb_zh.po zh.po
po-map appc_en.po appc_zh.po zh.po
po-map foreword_en.po foreword_zh.po zh.po
po-map ch00_en.po ch00_zh.po  zh.po
po-map ch01_en.po ch01_zh.po  zh.po
po-map ch02_en.po ch02_zh.po  zh.po
po-map ch03_en.po ch03_zh.po  zh.po
po-map ch04_en.po ch04_zh.po  zh.po
po-map ch05_en.po ch05_zh.po  zh.po
po-map ch06_en.po ch06_zh.po  zh.po
po-map ch07_en.po ch07_zh.po  zh.po
po-map ch08_en.po ch08_zh.po  zh.po
po-map ch09_en.po ch09_zh.po  zh.po
po-map ch09_02_en.po ch09_02_zh.po  zh.po
